machine: "ccao"
note: >
  Initial test

cv:
  split_prop: 0.9
  initial_set: 25
  max_iterations: 70
  no_improve: 30
  best_metric: "rmse"

model:
  predictor:
    all: [
      "meta_township_code",
      "meta_nbhd_code",
      "meta_modeling_group",
      "meta_tieback_proration_rate",
      "char_yrblt",
      "char_air",
      "char_apts",
      "char_attic_fnsh",
      "char_attic_type",
      "char_beds",
      "char_bldg_sf",
      "char_bsmt",
      "char_bsmt_fin",
      "char_ext_wall",
      "char_fbath",
      "char_frpl",
      "char_gar1_area",
      "char_gar1_att",
      "char_gar1_cnst",
      "char_gar1_size",
      "char_hbath",
      "char_land_sf",
      "char_heat",
      "char_ncu",
      "char_porch",
      "char_roof_cnst",
      "char_rooms",
      "char_tp_dsgn",
      "char_tp_plan",
      "char_type_resd",
      "char_recent_renovation",
      "loc_longitude",
      "loc_latitude",
      "loc_env_flood_fema_sfha",
      "loc_env_flood_fs_factor",
      "loc_env_flood_fs_risk_direction",
      "loc_env_airport_noise_dnl",
      "loc_school_elementary_district_geoid",
      "loc_school_secondary_district_geoid",
      "loc_access_cmap_walk_nta_score",
      "loc_access_cmap_walk_total_score",
      "loc_cook_municipality_name",
      "prox_num_pin_in_half_mile",
      "prox_num_bus_stop_in_half_mile",
      "prox_num_foreclosure_per_1000_pin_past_5_years",
      "prox_num_school_in_half_mile",
      "prox_num_school_with_rating_in_half_mile",
      "prox_avg_school_rating_in_half_mile",
      "prox_nearest_bike_trail_dist_ft",
      "prox_nearest_cemetery_dist_ft",
      "prox_nearest_cta_route_dist_ft",
      "prox_nearest_cta_stop_dist_ft",
      "prox_nearest_hospital_dist_ft",
      "prox_lake_michigan_dist_ft",
      "prox_nearest_major_road_dist_ft",
      "prox_nearest_metra_route_dist_ft",
      "prox_nearest_metra_stop_dist_ft",
      "prox_nearest_park_dist_ft",
      "prox_nearest_railroad_dist_ft",
      "prox_nearest_water_dist_ft",
      "prox_nearest_golf_course_dist_ft",
      "acs5_percent_age_children",
      "acs5_percent_age_senior",
      "acs5_median_age_total",
      "acs5_percent_mobility_no_move",
      "acs5_percent_mobility_moved_from_other_state",
      "acs5_percent_household_family_married",
      "acs5_percent_household_nonfamily_alone",
      "acs5_percent_education_high_school",
      "acs5_percent_education_bachelor",
      "acs5_percent_education_graduate",
      "acs5_percent_income_below_poverty_level",
      "acs5_median_income_household_past_year",
      "acs5_median_income_per_capita_past_year",
      "acs5_percent_income_household_received_snap_past_year",
      "acs5_percent_employment_unemployed",
      "acs5_median_household_total_occupied_year_built",
      "acs5_median_household_renter_occupied_gross_rent",
      "acs5_percent_household_owner_occupied",
      "acs5_percent_household_total_occupied_w_sel_cond",
      "acs5_percent_mobility_moved_in_county",
      "other_tax_bill_rate",
      "other_school_district_elementary_avg_rating",
      "other_school_district_secondary_avg_rating",
      "time_sale_year",
      "time_sale_day",
      "time_sale_quarter_of_year",
      "time_sale_month_of_year",
      "time_sale_day_of_year",
      "time_sale_day_of_month",
      "time_sale_day_of_week",
      "time_sale_post_covid"
    ]

    categorical: [
      "meta_township_code",
      "meta_nbhd_code",
      "meta_modeling_group",
      "char_air",
      "char_apts",
      "char_attic_fnsh",
      "char_attic_type",
      "char_bsmt",
      "char_bsmt_fin",
      "char_ext_wall",
      "char_gar1_area",
      "char_gar1_att",
      "char_gar1_cnst",
      "char_gar1_size",
      "char_heat",
      "char_porch",
      "char_roof_cnst",
      "char_tp_dsgn",
      "char_tp_plan",
      "char_type_resd",
      "loc_cook_municipality_name",
      "loc_school_elementary_district_geoid",
      "loc_school_secondary_district_geoid",
      "time_sale_quarter_of_year"
    ]

    id: [
      "meta_year",
      "meta_pin",
      "meta_class",
      "meta_card_num",
      "meta_sale_document_num"
    ]

  lightgbm:
    engine: "lightgbm"
    objective: "rmse"
    seed: 2023
    verbose: 2

    parameter:
      num_iterations: 2000
      learning_rate: 0.025
      link_max_depth: TRUE
      max_bin: 512
      stop_iter: 40

      validation_prop: 0
      validation_type: "recent"
      validation_metric: "rmse"

    hyperparameter:
      num_leaves: 1300
      add_to_linked_depth: 4
      feature_fraction: 0.475
      min_gain_to_split: 5.5
      min_data_in_leaf: 4
      max_cat_threshold: 200
      min_data_per_group: 75
      cat_smooth: 40.0
      cat_l2: 1.00
      lambda_l1: 0.124
      lambda_l2: 1.655
